# Generated by Django 2.0.7 on 2018-10-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webUI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
