# Generated by Django 2.0.7 on 2018-10-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webUI', '0002_auto_20181008_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='choice',
            field=models.IntegerField(choices=[(1, '超级'), (2, '一般'), (3, '渣渣')], default=2),
        ),
    ]
