# Generated by Django 2.0.7 on 2018-10-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webUI', '0003_host_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='choice',
            field=models.CharField(choices=[('M', '男'), ('W', '女'), ('S', '保密')], default='S', max_length=1),
        ),
    ]
