# Generated by Django 2.0.7 on 2018-10-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webUI', '0005_auto_20181008_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='other',
            field=models.IntegerField(default=0),
        ),
    ]
