# Generated by Django 2.0.7 on 2018-10-08 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webUI', '0006_host_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='choices',
        ),
    ]
