# Generated by Django 2.0.7 on 2018-10-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webUI', '0007_remove_host_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='other',
        ),
        migrations.AddField(
            model_name='host',
            name='choices',
            field=models.CharField(choices=[('M', '男'), ('W', '女'), ('S', '保密')], default='S', max_length=1),
        ),
    ]
